VT-5843 Lightspeed: Product Sync Mapping Updates
skuvault-integrations/lightspeedAccess pull request #11
Opened 2023-01-27 09:20 UTC by mrassudishkin

Added request for Vendors because we need this data for mapping Suppliers in SkuVault

2023-01-27 09:32 UTC, dk-skuvault commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				var vendor = vendors.FirstOrDefault( x => x.VendorId == product.DefaultVendorId );
How much vendors can we have? Can this place be potentially slow? Should we use join or dictionary with vendorId as key?

2023-01-27 09:32 UTC, dk-skuvault commented on src/lightspeedAccess/LightspeedProductsService.cs
> +		private async Task< IEnumerable< LightspeedVendor > > ExecuteGetVendorsRequest( GetVendorsRequest request, CancellationToken ctx )
Could you add new tests for the new code?

2023-01-27 09:33 UTC, dk-skuvault commented
Please add ticket number to the description

2023-01-27 09:51 UTC, andrey-kozlov-skuvault commented on src/lightspeedAccess/LightspeedProductsService.cs
> +		private async Task< IEnumerable< LightspeedVendor > > ExecuteGetVendorsRequest( GetVendorsRequest request, CancellationToken ctx )
If we do not have unit tests here - can we add integration test that could check that vendor name is loaded?

2023-01-27 11:19 UTC, mrassudishkin commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				var vendor = vendors.FirstOrDefault( x => x.VendorId == product.DefaultVendorId );
Added dictionary

2023-01-27 11:21 UTC, mrassudishkin commented on src/lightspeedAccess/LightspeedProductsService.cs
> +		private async Task< IEnumerable< LightspeedVendor > > ExecuteGetVendorsRequest( GetVendorsRequest request, CancellationToken ctx )
Added Assert to integration test

2023-01-27 11:32 UTC, andrey-kozlov-skuvault approved these changes

2023-01-30 03:11 UTC, slav requested changes

2023-01-30 03:11 UTC, slav commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				.ToDictionary( k => k.VendorId, v => v.Name );
VendorId is guaranteed to be unique here? Just bringing up as if it's not it'll throw an exception

2023-01-30 06:19 UTC, mrassudishkin commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				.ToDictionary( k => k.VendorId, v => v.Name );
I can't give guarante here because this is response from Lightspeed. It would was strange but I added 'group by' for this situation.

2023-01-30 09:54 UTC, dk-skuvault commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				.ToDictionary( k => k.VendorId, v => v.Name );
Can we check their API documentation? I would not complicate logic without a reason.

2023-01-30 10:03 UTC, mrassudishkin commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				.ToDictionary( k => k.VendorId, v => v.Name );
This is unique field of course - if we believe documentation. @slav Do we agree lightspeed documentation?

2023-01-30 14:19 UTC, gregarican commented
Looking at their API docs, this field appears to be a unique ID. Which follows suit with their other endpoints and their ID fields.


<html>
<body>
<!--StartFragment-->

vendorID | (integer) The unique numerical ID for the vendor.

<!--EndFragment-->
</body>
</html>

2023-01-31 01:13 UTC, slav commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				.ToDictionary( k => k.VendorId, v => v.Name );
@mrassudishkin if we get bad data, are we going to just throw just skip a little bit of information? Or are we going to fail sync and will continue to fail until either lightspeed fixes it on their end or we implement a fix?

General rule of thumb, never trust data coming from outside. So, if bad data can cause bad situation (such as integration cannot complete and sync always fails until fixed) then we need to do something about it. It doesn't sound like it should be very hard? I thought we already had somewhere ToDictionarySafe method or similar where it won't throw but just ignores double key or null key or whatever?

2023-01-31 11:31 UTC, dk-skuvault commented on src/lightspeedAccess/LightspeedProductsService.cs
> +				.ToDictionary( k => k.VendorId, v => v.Name );
Okay

2023-02-02 22:59 UTC, slav approved these changes

2023-03-15 07:39 UTC, merged