VT-5571 Lightspeed Products Sync
skuvault-integrations/lightspeedAccess pull request #8
Opened 2022-09-19 09:19 UTC by mrassudishkin

Added service for products sync without refactoring. This service is extended variant of inventory sync but I created separate files for it.

2022-09-19 12:35 UTC, andrey-kozlov-skuvault reviewed
Do not see unit tests here at all, but probably these are not required for the new service and this PR, as its logic is pretty straightforward.
I see a bunch of untested logic in e.g. reqeusts or web service - but these tests should be added as a separate task or be a part of a general refactoring, I believe.

2022-09-19 12:35 UTC, andrey-kozlov-skuvault commented on src/lightspeedAccess/Models/Request/GetProductRequest.cs
> +	public class GetProductRequest : LightspeedRequest
Cannot find usages of this class - is it really needed?

2022-09-19 12:35 UTC, andrey-kozlov-skuvault commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		}
Do we need separate methods for these - maybe just use public proeperties with appropriately accessible getters/settters?

2022-09-19 12:35 UTC, andrey-kozlov-skuvault commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		public enum ArchivedOptionEnum
If this enum is not intended to be used somewhere else (looks like no, as cannot find usages) - maybe make it private.
Otherwise it should be declared in a separate file.

2022-09-21 12:32 UTC, mrassudishkin commented
> Do not see unit tests here at all, but probably these are not required for the new service and this PR, as its logic is pretty straightforward. I see a bunch of untested logic in e.g. reqeusts or web service - but these tests should be added as a separate task or be a part of a general refactoring, I believe.

Yes, you are right, we decided make this ticket without refactoring.

2022-09-21 12:32 UTC, mrassudishkin commented on src/lightspeedAccess/Models/Request/GetProductRequest.cs
> +	public class GetProductRequest : LightspeedRequest
Removed

2022-09-21 12:32 UTC, mrassudishkin commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		}
Removed it

2022-09-21 12:33 UTC, mrassudishkin commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		public enum ArchivedOptionEnum
Unused here so removed it

2022-09-21 13:48 UTC, andrey-kozlov-skuvault commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		}
What about other methods, like GetOffset, SetOffset, GetLimit?
Looks like this could be replaced with propery with corresponding access, if needed

2022-09-22 06:41 UTC, mrassudishkin commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		}
This is part of interface IRequestPagination. I don't want to rewrite this code here.

2022-09-22 12:21 UTC, andrey-kozlov-skuvault commented on src/lightspeedAccess/Models/Request/GetProductsRequest.cs
> +		}
Ah, I see. Yep, no need to refactor such a things here

2022-09-22 12:22 UTC, andrey-kozlov-skuvault approved these changes

2022-09-26 10:01 UTC, dk-skuvault approved these changes

2022-10-03 12:51 UTC, andrey-kozlov-skuvault approved these changes

2022-10-11 17:40 UTC, slav commented on src/lightspeedAccess/Models/Product/LightspeedFullProduct.cs
> +			if( otherTyped != null )
Not sure if this was generated or not, but this is typical &&, can do just `if( otherTyped != null && otherTyped.Item != null)`

2022-10-11 17:41 UTC, slav commented on src/lightspeedAccess/Models/Product/LightspeedProduct.cs
> +
Why did we add this tab here?

2022-10-11 17:42 UTC, slav requested changes
a couple of small comments

2022-10-25 07:37 UTC, mrassudishkin commented on src/lightspeedAccess/LightspeedProductsService.cs
> +			LightspeedLogger.Debug( $"Started LightspeedProductsService with config {config}", this._accountId );
This isn't Log.Debug, It's just string.Format. If you want that I make it then I will should to refactore LightspeedLoger and update a lot of places. I wouldn't do it here.

2022-10-25 07:39 UTC, mrassudishkin commented on src/lightspeedAccess/Models/Product/LightspeedProduct.cs
> +
Done

2022-10-25 07:39 UTC, mrassudishkin commented on src/lightspeedAccess/Models/Product/LightspeedFullProduct.cs
> +			if( otherTyped != null )
Done

2022-10-25 20:28 UTC, slav commented on src/lightspeedAccess/LightspeedProductsService.cs
> +			LightspeedLogger.Debug( $"Started LightspeedProductsService with config {config}", this._accountId );
Are we using common template though? If not, should we create a ticket? Or doesn't matter as we expect this lightspeed integration to go away?

2022-10-25 20:28 UTC, slav approved these changes
approved, but with comment about logging

2022-10-26 05:56 UTC, mrassudishkin commented on src/lightspeedAccess/LightspeedProductsService.cs
> +			LightspeedLogger.Debug( $"Started LightspeedProductsService with config {config}", this._accountId );
I think that it will better make in ticket for refactoring.

2022-10-27 06:23 UTC, merged